#!/bin/bash
pastdate=$(<lastdatetime)
echo $(date +"%Y-%m-%d %T") > lastdatetime
mysql -u root -pHealthydogsandcats -e 'USE ConnectBasket; SELECT `Recipient`,`Body` FROM `Messages` WHERE `DBCreateDate` >= "$(pastdate)"' --skip-column-names -B > newmessages
if (( $(wc -c newfile | cut -f1 -d" ") == 0 )) 
	then 
		while IFS='' read -r line || [[ -n "$line" ]]; do
			token=( $line )
			echo "$(date)  ---  Sending message to ${token[0]}. Message body: ${token[@]:1}" >> emaillog.file
			emailaddress=$(mysql -u root -pHealthydogsandcats -e 'USE ConnectBasket; SELECT `EmailAddress` FROM `Users` WHERE `Username` = "${token[0]}"' --skip-column-names -B)
			mailx -s “New ConnectBasket Messages” $emailaddress < message.txt
		done < newmessages
fi
